### ISSUE TITLE
[DocDB] GetCheckpoint and SetCheckpoint RPC can get stuck in a spawn loop for a non-leader peer

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#17123]
Jira Link: [DB-6408](https://yugabyte.atlassian.net/browse/DB-6408)
### Description

`CDCServiceImpl::GetCheckpoint()` / `CDCServiceImpl::SetCDCCheckpoint()` can fall into an "infinite" RPC loop for the same tserver if meta-cache has stale leader information.

Became visible due to https://github.com/yugabyte/yugabyte-db/commit/3272f36005a58aee4b6b1bf395cf575e433279d6

The mentioned commit changes the algo for calculating the number of tablets on base of CPU cores and tablet splitting activation: if num of CPU cores ≤ 4 and automatic tablet splitting is on then we are getting 1 or 2 tablets per table, and previously we were getting num tablets == num TS when automatic tablet splitting is on. The issue can be easily hit on a machine with ≤ 4 cores.
Looks like the less number of tablets gives some kind of imbalance and at some point (actually right after [this](https://github.com/yugabyte/yugabyte-db/blob/b9e0efa3ece77015cd886de7dfd14ee91cadadfc/src/yb/integration-tests/cdcsdk_before_image-test.cc#L180) line) load balancer decides to move a tablet leader of test table (it has 1 tablet):
```
I0503 00:01:49.365402 11382 cdcsdk_before_image-test.cc:185] Sleeping to expire files according to TTL (history retention prevents deletion)
[m-1] I0503 00:01:49.813832 11417 cluster_balance.cc:1430] Moving leader of a652791fa8fb43b88cc9e1b14be0a2fc from TS 4175e5470b1f47a6a003d1cef880438e (ts-3) to d9f8a472b95d4df3b4926250658321f1 (ts-2)
```
If tablet peer is not a leader, then CDCService on this TS is trying to identify the leader and trigger `CDCServiceImpl::GetCheckpoint(`) on the leader:
```
Result<RemoteTabletServer*> CDCServiceImpl::GetLeaderTServer(const TabletId& tablet_id) {
  auto result = VERIFY_RESULT(GetRemoteTablet(tablet_id));
  auto ts = result->LeaderTServer();
```
And `GetRemoteTablet()`  relies on client [lookup](https://github.com/yugabyte/yugabyte-db/blob/b9e0efa3ece77015cd886de7dfd14ee91cadadfc/src/yb/client/client.cc#L2138) method, which triggers meta cache lookup:
```
Result<client::internal::RemoteTabletPtr> CDCServiceImpl::GetRemoteTablet(…
   …
  client()->LookupTabletById(…);
```
But meta cache may contain stale information for replicas’ leader and return previous old leader — this is considered a valid behaviour as old leader should respond with ‘Not a leader’ error (or something like this) for other operations, which should trigger a chain of meta cache / remote tablet replicas refresh with further retry to a real leader. But `GetCheckpoint`/`SetCDCCheckPoint` has no protection of re-directing an RPC to the de facto non-leader tablet peer. And that's why `GetCheckpoint`/`SetCDCCheckPoint` falls into a loop of spawning RPCs to the old TS. Tones of messages (with additional test traces) about trying to `TabletLeaderGetCheckpoint` can be seen in the logs:
```
I0503 00:01:54.366101 11382 cdcsdk_ysql_test_base.h:1105] TEST: get checkpoint for: a652791fa8fb43b88cc9e1b14be0a2fc
[ts-1] I0503 00:01:54.367672 11471 cdc_service.cc:2941] TEST: CDCServiceImpl::GetCheckpoint
[ts-1] I0503 00:01:54.367898 11471 cdc_service.cc:2964] TEST: CDCServiceImpl::GetCheckpoint requesting for leader checkpoint: is_leader: -
[ts-1] I0503 00:01:54.367941 11471 meta_cache.cc:2166] TEST: MetaCache::LookupTabletById: a652791fa8fb43b88cc9e1b14be0a2fc, uc: 1
[ts-3] I0503 00:01:54.368779 11773 cdc_service.cc:2941] TEST: CDCServiceImpl::GetCheckpoint
[ts-3] I0503 00:01:54.368928 11773 cdc_service.cc:2964] TEST: CDCServiceImpl::GetCheckpoint requesting for leader checkpoint: is_leader: -
[ts-3] I0503 00:01:54.368959 11773 meta_cache.cc:2166] TEST: MetaCache::LookupTabletById: a652791fa8fb43b88cc9e1b14be0a2fc, uc: 1
[ts-3] I0503 00:01:54.370335 11602 cdc_service.cc:2941] TEST: CDCServiceImpl::GetCheckpoint
[ts-3] I0503 00:01:54.370476 11602 cdc_service.cc:2964] TEST: CDCServiceImpl::GetCheckpoint requesting for leader checkpoint: is_leader: -
[ts-3] I0503 00:01:54.370507 11602 meta_cache.cc:2166] TEST: MetaCache::LookupTabletById: a652791fa8fb43b88cc9e1b14be0a2fc, uc: 1
...
../../src/yb/integration-tests/cdcsdk_before_image-test.cc:192: Failure
Failed
Bad status: Timed out (yb/rpc/outbound_call.cc:489): GetCheckpoint RPC (request call id 2371) to 127.0.0.2:27451 timed out after 60.000s
[ts-3] I0503 00:02:54.371838 11773 cdc_service.cc:2941] TEST: CDCServiceImpl::GetCheckpoint
[ts-3] I0503 00:02:54.372009 11773 cdc_service.cc:2964] TEST: CDCServiceImpl::GetCheckpoint requesting for leader checkpoint: is_leader: -
[ts-3] I0503 00:02:54.372042 11773 meta_cache.cc:2166] TEST: MetaCache::LookupTabletById: a652791fa8fb43b88cc9e1b14be0a2fc, uc: 1
...
[ts-3] I0503 00:03:04.220142 11382 raft_consensus.cc:2780] T 18cd1f3a35b64006aa0791bd3648e831 P 4175e5470b1f47a6a003d1cef880438e [term 1 LEADER]: Raft consensus is shut down!
[ts-3] I0503 00:03:04.220247 12608 cdc_service.cc:2941] TEST: CDCServiceImpl::GetCheckpoint
[ts-3] I0503 00:03:04.220342 12608 cdc_service.cc:2964] TEST: CDCServiceImpl::GetCheckpoint requesting for leader checkpoint: is_leader: -
[ts-3] I0503 00:03:04.220366 12608 meta_cache.cc:2166] TEST: MetaCache::LookupTabletById: a652791fa8fb43b88cc9e1b14be0a2fc, uc: 1
[ts-3] W0503 00:03:04.233925 11548 service_pool.cc:237] yb.cdc.CDCService: GetCheckpoint request on yb.cdc.CDCService from 127.0.0.6:35617 dropped because of: Aborted (yb/rpc/thread_pool.cc:257): Service is shutting down
[m-1] W0503 00:03:04.454437 11417 scoped_leader_shared_lock.cc:167] RPC took a long time (../../src/yb/master/catalog_manager_bg_tasks.cc:163, Run): 1.635s
...
```

The issue has been confirmed with @suranjan.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6408]: https://yugabyte.atlassian.net/browse/DB-6408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
Note, as per offline discussion with @suranjan and @adithya-yb , this is a product issue and will require backporting.

**Comment by arybochkin** [comment]
@adithya-yb, did the issue fixed in the context of https://github.com/yugabyte/yugabyte-db/issues/17165? if yes, please close the ticket.

**Comment by adithya-yb** [comment]
@arybochkin  , yes the fix for https://github.com/yugabyte/yugabyte-db/issues/17165 also fixes this issue.

**Comment by bmatican** [comment]
@arybochkin I had tagged https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=QLTransactionTest&fail_tag=all&name=IntentsCleanupAfterRestart&platform=linux also with this issue, but seems this did not get fixed by Adithya's change, so it might be that your splitting related change affected this test different? perhaps we need a separate GH issue and investigation for this one?

**Comment by arybochkin** [comment]
@bmatican, I've filed https://github.com/yugabyte/yugabyte-db/issues/17330 and re-muted the test with new GH issue.

**Comment by arybochkin** [comment]
@adithya-yb, the tests are still failing, they require additional hardening. please track additional changes by this issue or file a separate GH.

CDCSDKYsqlTest.TestBeforeImageExpiration (rare):
CDCSDKYsqlTest.TestExpiredStreamWithCompaction (rare):
CDCSDKYsqlTest.TestMultipleTableAlterWithBeforeImage (rare):
```
../../src/yb/integration-tests/cdcsdk_ysql-test.cc:5881
Failed
Bad status: Internal error (yb/integration-tests/cdcsdk_ysql_test_base.h:1090): Response had error: error {
  code: LEADER_NOT_READY
  status {
    code: LEADER_NOT_READY_TO_SERVE
    message: "Not ready to serve: LEADER_NOT_READY"
    source_file: "../../src/yb/cdc/cdc_service.cc"
    source_line: 1194
    errors: "\020\013\000\000\000\000"
  }
}
```
CDCSDKYsqlTest.TestBeforeImageExpiration (rare):
```
../../src/yb/integration-tests/cdcsdk_ysql_test_base.h:1183
Expected equality of these values:
  value
    Which is: 3
  record.row_message().new_tuple(index).datum_int32()
    Which is: 2
```
CDCSDKYsqlTest.TestMultipleTableAlterWithBeforeImage (very often):
```
../../src/yb/integration-tests/cdcsdk_ysql_test_base.h:1179
Expected equality of these values:
  key
    Which is: 0
  record.row_message().new_tuple(0).datum_int32()
    Which is: 1
```

Also please apply remaining comments from the original review with tests hardening, that were provided with the revision acceptance.

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=CDCSDKYsqlTest&fail_tag=all&name=TestExpiredStreamWithCompaction&platform=linux
https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=CDCSDKYsqlTest&fail_tag=all&name=TestBeforeImageExpiration&platform=linux
https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&build_type=all&class=CDCSDKYsqlTest&fail_tag=all&name=TestMultipleTableAlterWithBeforeImage&platform=linux

cc @bmatican

**Comment by rthallamko3** [comment]
@suranjan , Since this issue has been fixed in master, can we get someone to backport to stable branches and close out this issue?

**Comment by rthallamko3** [comment]
Per Aditya's comment above, fix for https://github.com/yugabyte/yugabyte-db/issues/17165 solves this problem as well. The fix for https://github.com/yugabyte/yugabyte-db/issues/17165 has been backported to stable branches, all the way back to 2.14. Closing this issue. cc @suranjan
