### ISSUE TITLE
[YSQL] AlreadyPresent could mean duplicate Raft records or unique index violation

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#3244]
In YSQL we consider AlreadyPresent to be a "duplicate key" error:
```c
bool YBCStatusIsDuplicateKey(YBCStatus s) {
  return StatusWrapper(s)->IsAlreadyPresent();
}
```

and then

```c
/*
 * Utility method to handle the status of an insert statement to return unique
 * constraint violation error message due to duplicate key in primary key or
 * unique index / constraint.
 */
static void YBCHandleInsertStatus(YBCStatus status, Relation rel, YBCPgStatement stmt)
{
	if (!status)
		return;

	HandleYBStatus(YBCPgDeleteStatement(stmt));

	if (YBCStatusIsDuplicateKey(status))
	{
		char *constraint;

		/*
		 * If this is the base table and there is a primary key, the primary key is
		 * the constraint. Otherwise, the rel is the unique index constraint.
		 */
		if (!rel->rd_index && rel->rd_pkindex != InvalidOid)
		{
			Relation pkey = RelationIdGetRelation(rel->rd_pkindex);

			constraint = pstrdup(RelationGetRelationName(pkey));

			RelationClose(pkey);
		}
		else
		{
			constraint = pstrdup(RelationGetRelationName(rel));
		}

		YBCFreeStatus(status);
		ereport(ERROR,
				(errcode(ERRCODE_UNIQUE_VIOLATION),
				 errmsg("duplicate key value violates unique constraint \"%s\"",
						constraint)));
	}
	else
	{
		HandleYBStatus(status);
	}
}
```

However, AlreadyPresent could be thrown by the tserver as part of request deduplication:
```c++
    if (it != replicated_indexed_by_last_id.end() && it->first_id <= data.request_id()) {
      round->NotifyReplicationFinished(
          STATUS(AlreadyPresent, "Duplicate request"), round->bound_term(),
          nullptr /* applied_op_ids */);
      return false;
    }
```
and
```c++
    static Status duplicate_write_status = STATUS(AlreadyPresent, "Duplicate request");
    auto status_for_duplicate = status.ok() ? duplicate_write_status : status;
    for (const auto& duplicate : running_it->duplicate_rounds) {
      duplicate->NotifyReplicationFinished(status_for_duplicate, leader_term,
                                           nullptr /* applied_op_ids */);
    }
```
(in retryable_requests.cc).

We need to distinguish the two kinds of AlreadyPresent errors, and handle AlreadyPresent errors originating from the request deduplication subsystem differently.

Users have also reported that unique constraint violation errors can be observed even for non-unique indexes, which is consistent with the above theory.

**Comment by mbautin** [comment]
Some more input from @nocaway:

> The real issue is that the AlreadyPresent status is overloaded at the lower level.  As a result sometimes, it's an actual error, and sometimes it's not.  The status should have been something such as negative-status = actual error, zero-status = success, and positive-status = log or warning.

**Comment by mbautin** [comment]
Also @ndeodhar pointed out that this was fixed in a5a0f7dafde1756f9dd3015ddcd5e78143a30b12 but possibly broken again in 482a0d2864a0973570be9fc9343383f8e5690a5e.

**Comment by kmuthukk** [comment]
raising priority, since it is a regression.

**Comment by mbautin** [comment]
@nocaway After some discussion with @spolitov, the AlreadyPresent error that happens when rejecting duplicate requests on timeout retries is not something we can silently ignore on the server side, at least not in a straightforward way. This "retryable request" handling logic was introduced to fix Jepsen issues that happened when e.g. we send a request, get a timeout due to network partition, then get a successful response on a retry, but then some time later the original request reaches the tablet server and performs another write to the same key, perhaps overwriting some data that was written after the client got a reply to the original request. With the "duplicate request" detection system this scenario would be handled, and only one copy of each write request would be replicated in the Raft log, while all other copies (retries) would be rejected with this error. The reason for not being able to transparently handle these AlreadyPresent errors on the server side that @spolitov mentioned is that e.g. an INSERT statement has to return the number of rows inserted. Now consider a scenario when an INSERT request results in Write RPC from the postgres process to the tablet server, which times out and is retried, but in fact is handled on the server side. Then on the retry we get an "Already present: duplicate write" error. The INSERT must have happened but we still have to respond to the client with the number of rows inserted, and this information is not available as part of the reply that we got from the server. We could assume that if the original request was successfully replicated, then the requested number of rows that should have been inserted got successfully inserted. Would this always be correct? Are there more details we have to keep in mind?

**Comment by iSignal** [comment]
After https://github.com/yugabyte/yugabyte-db/commit/2166ff8c0616005efa4be8b8bcf45a81124090c3 this issue no longer happens for YSQL txns as they pick a read time set on the client and are now considered successful on the retry. However, for fast path updates, this can still happen as the read time is picked on the remote tserver. https://github.com/iSignal/yugabyte-db/blob/0c31be1a9f083405b4213bf566595944ee6242d6/src/yb/yql/pgwrapper/pg_lost_write_response-test.cc#L66 has a test that fails to show this issue.

As mentioned in the GH ticket description, there are two issues here 
1. retry could hit a duplicate check for unique index
2. retry may be returned to PG client as a failure.

@pao214 @sushantrmishra @neera-mital @spolitov
